version: '3.7'

services:
  system:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: system_info
      POSTGRES_USER: stewie
      POSTGRES_PASSWORD: stewie
    ports:
      - "5432:5432"