spring:
  datasource:
    name: ${SPRING_DATASOURCE_USERNAME:stewie}
    password: ${SPRING_DATASOURCE_PASSWORD:stewie}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/system_info}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql


model:
  vars:
    alpha: 1
    beta: 0
    lambda: 5
    sources: 15
    devices: 3
    requests: 2000
    buffer: 10